#!/bin/bash
# Backup script for VPS2 (DATA server)
# Sets up PostgreSQL backup cron job
# Usage: ./70_backups.sh --host HOST [OPTIONS]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../lib"

# Source library functions
source "$LIB_DIR/common.sh"
source "$LIB_DIR/ssh.sh"
source "$LIB_DIR/assert.sh"

show_help() {
    cat <<EOF
Usage: $(basename "$0") --host HOST [OPTIONS]

Sets up PostgreSQL backup cron job on VPS2 (DATA server).

Options:
    --dry-run           Show what would be done without making changes
    --host HOST         Target host (required, should be VPS2)
    --help, -h          Show this help message

EOF
}

setup_backup_directory() {
    local host="$1"
    local user="${2:-root}"
    local port="${3:-22}"
    local backup_dir="${BACKUP_DIR:-/backup}"
    
    log_info "Setting up backup directory: $backup_dir"
    
    ssh_exec_sudo "$host" "$user" "$port" "
        mkdir -p $backup_dir
        chmod 700 $backup_dir
        chown postgres:postgres $backup_dir
    "
}

create_backup_script() {
    local host="$1"
    local user="${2:-root}"
    local port="${3:-22}"
    local backup_dir="${BACKUP_DIR:-/backup}"
    local db_name="${POSTGRES_DB:-orcazap}"
    local db_user="${POSTGRES_USER:-orcazap}"
    local db_password="${POSTGRES_PASSWORD:-}"
    local retention_days="${BACKUP_RETENTION_DAYS:-7}"
    
    if [ -z "$db_password" ]; then
        log_error "POSTGRES_PASSWORD not set in inventory"
        exit 1
    fi
    
    log_info "Creating backup script"
    
    local backup_script="/tmp/postgres-backup.sh.$$"
    cat > "$backup_script" <<EOF
#!/bin/bash
# PostgreSQL backup script
# Generated by OrcaZap infrastructure automation

set -euo pipefail

BACKUP_DIR="$backup_dir"
DB_NAME="$db_name"
DB_USER="$db_user"
DB_PASSWORD="$db_password"
RETENTION_DAYS=$retention_days

export PGPASSWORD="\$DB_PASSWORD"

# Create backup
BACKUP_FILE="\$BACKUP_DIR/orcazap-\$(date +%Y%m%d_%H%M%S).sql.gz"
pg_dump -h 127.0.0.1 -U "\$DB_USER" "\$DB_NAME" | gzip > "\$BACKUP_FILE"

# Set permissions
chmod 600 "\$BACKUP_FILE"
chown postgres:postgres "\$BACKUP_FILE"

# Remove old backups
find "\$BACKUP_DIR" -name "orcazap-*.sql.gz" -type f -mtime +\$RETENTION_DAYS -delete

# Log
echo "\$(date): Backup created: \$BACKUP_FILE" >> /var/log/postgres-backup.log
EOF
    
    # Copy to remote host
    ssh_copy_file "$host" "$user" "$port" "$backup_script" "/tmp/postgres-backup.sh"
    
    # Move to final location
    ssh_exec_sudo "$host" "$user" "$port" "
        mv /tmp/postgres-backup.sh /usr/local/bin/postgres-backup.sh
        chmod +x /usr/local/bin/postgres-backup.sh
        chown root:root /usr/local/bin/postgres-backup.sh
    "
    
    # Clean up
    rm -f "$backup_script"
}

setup_cron_job() {
    local host="$1"
    local user="${2:-root}"
    local port="${3:-22}"
    
    log_info "Setting up daily cron job"
    
    ssh_exec_sudo "$host" "$user" "$port" "
        # Remove existing cron job if present
        crontab -u postgres -l 2>/dev/null | grep -v postgres-backup.sh | crontab -u postgres - || true
        
        # Add new cron job (daily at 2 AM)
        (crontab -u postgres -l 2>/dev/null; echo '0 2 * * * /usr/local/bin/postgres-backup.sh') | crontab -u postgres -
    "
}

main() {
    init_script "$@"
    load_inventory
    
    if [ -z "${TARGET_HOST:-}" ]; then
        TARGET_HOST="${VPS2_HOST:-}"
    fi
    
    if [ -z "$TARGET_HOST" ]; then
        log_error "Target host not specified. Use --host HOST or set VPS2_HOST"
        show_help
        exit 1
    fi
    
    # Should be VPS2
    if [ "$TARGET_HOST" != "${VPS2_HOST:-}" ]; then
        log_warning "This script is intended for VPS2 (DATA server). Continuing anyway..."
    fi
    
    local ssh_user="${VPS2_SSH_USER:-root}"
    local ssh_port="${VPS2_SSH_PORT:-22}"
    
    log_info "Setting up backups on $TARGET_HOST"
    
    # Assert SSH connection
    assert_ssh_connection "$TARGET_HOST" "$ssh_user" "$ssh_port"
    
    # Validate required variables
    validate_required_vars POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD
    
    setup_backup_directory "$TARGET_HOST" "$ssh_user" "$ssh_port"
    create_backup_script "$TARGET_HOST" "$ssh_user" "$ssh_port"
    setup_cron_job "$TARGET_HOST" "$ssh_user" "$ssh_port"
    
    log_success "Backup setup completed"
}

main "$@"


